name: get_it_starter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  get_it: 7.6.7

dev_dependencies:
  flutter_lints: 3.0.1